carsaleswebsiteproject/car_management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('details/<int:pk>/', views.CarDetailsPageView.as_view(), name="carDetailspage"),
    path('shop/details/<int:pk>/', views.CarDetailsPageViewshop.as_view(), name="carDetailspageshop"),
    # path('user/<int:pk>/', views.buy_car, name='buy_car'),
    path('car/comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('contact/', views.contactPage, name="contact"),
    path('shop/<slug:brand_slug>/', views.car_list, name='car_list_by_brand'),
    path('shop/', views.car_list, name="shoppage"),
    path('<slug:brand_slug>/', views.homepage, name='car_list_by_brand_index'),
]

carsaleswebsiteproject/carsaleswebsiteproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_management.urls')),
    path('profile/', include('user_management.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carsaleswebsiteproject/car_management/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return self.name

class Car(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='car_management/media/car_images')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    comment = models.TextField()

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.id}-{self.car}-{self.user}"

carsaleswebsiteproject/car_management/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import *
from .models import *

# Create your views here.
def homepage(request, brand_slug=None):
    cars = Car.objects.all()
    brands = Brand.objects.all()
    if brand_slug is not None:
        brand = Brand.objects.get(slug = brand_slug)
        cars = Car.objects.filter(brand = brand)
    return render(request, 'car_management/index.html', {'cars':cars, 'brands':brands})

def car_list(request, brand_slug=None):
    cars = Car.objects.all()
    brands = Brand.objects.all()
    if brand_slug is not None:
        brand = Brand.objects.get(slug = brand_slug)
        cars = Car.objects.filter(brand = brand)
    return render(request, 'car_management/car_list.html', {'cars':cars, 'brands':brands})


def contactPage(request):
    return render(request, './car_management/contact.html')



class CarDetailsPageView(DetailView):
    model = Car
    template_name = 'car_management/car_details.html'
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        car = self.get_object()
        return render(request, self.template_name,{'car': car})
    

class CarDetailsPageViewshop(DetailView):
    model = Car
    template_name = 'car_management/car_details.html'
    pk_url_kwarg = 'pk'
    def get(self, request, *args, **kwargs):
        car = self.get_object()
        return render(request, self.template_name, {'car': car})


def add_comment(request, pk):
    car = get_object_or_404(Car, pk=pk)
    if request.method == 'POST':
        name = request.POST.get('name')
        comment_text = request.POST.get('comment')
        if request.user.is_authenticated:
            Comment.objects.create(user=request.user, car=car, name=name, comment=comment_text)
        else:
            Comment.objects.create(user=None, car=car, name=name, comment=comment_text)
    return render(request, 'car_management/car_details.html', {'car': car})

carsaleswebsiteproject/car_management/templates/car_management/car_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Car Details- {{car.name}} {% endblock  %}

{% block content %}


<div class="d-flex align-center justify-content-center">
    <div class="card">
        <div class="card-body row">
            <div class="col-md-5">
                <img src="{{ car.image.url }}" alt="{{ car.name }} Image" class="img-fluid">
            </div>
            <div class="col-md-7">
                
                <p>Name: {{ car.name }}</p>
                <p>Price: ${{ car.price }}</p>
                <p>Quantity: {{ car.quantity }}</p>
                <p style="max-width:300px;">Description: {{ car.description }}</p>
                <p>Quantity: {{ car.brand }}</p>
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'buy_car' car.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Buy Now</button>
                </form>
                {% else %}
                    <a href="{% url 'login' %}" class="btn btn-info">Login To Buy</a>
                {% endif %}

            </div>
        </div>
    </div>
</div>
<div class="d-flex align-center justify-content-center row">
    <div class="col-md-12">
        <h3>Comments</h3>
        {% for comment in car.comments.all %}
            <p><strong>{{ comment.name }}:</strong> {{ comment.comment }}</p>
        {% endfor %}
    </div> 
</div>
 <div class="d-flex align-center justify-content-center row">
    <div class="col-md-12">
       
        <form method="post" action="{% url 'add_comment' pk=car.pk %}">

          {% csrf_token %}
          <label for="id_name">Name:</label>
          <input type="text" name="name" id="id_name" required>
          <br>
          <label for="id_comment">Comment:</label>
          <textarea name="comment" id="id_comment" rows="4" required></textarea>
          <br>
          <button type="submit">Add Comment</button>
        </form>
      
    </div> 
</div> 

{% endblock  %}

carsaleswebsiteproject/car_management/templates/car_management/car_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Shop List{% endblock  %}

{% block content %}

<div class="d-flex align-center justify-content-center row mt-5">
    <div class="card">
    
        <div class="card-header">
            <div class="row d-flex">
                <div class="col">
                    <a class="nav-link" href="{% url 'shoppage' %}">All</a>
                </div>
                {% for brand in brands %}
                <div class="col">
                    <a class="nav-link" href="{% url 'car_list_by_brand' brand.slug %}">{{brand.name}}</a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-body">
            <h5>Showing {{ cars | length }} items</h5>
            <div class="row"> 
                {% for car in cars %}
                    <div class="col-md-4">
                        <div class="card my-2" >
                            <img src="{{ car.image.url }}" class="card-img-top" alt="{{ car.name }}">
                            <div class="card-body">
                                <h5>{{ car.name }}</h5>
                                <p class="text-muted">${{ car.price }}</p>
                                <p ><span class="badge bg-info">{{ car.brand}}</span></p>
                                <a href="{% url 'carDetailspageshop' car.id %}" class="btn btn-warning">View Details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    
               
            </div>
        </div>

        
    </div>
</div>


{% endblock  %}

carsaleswebsiteproject/car_management/templates/car_management/contact.html
{% extends 'base.html' %} 
{% load static  %} 
{% block title %}Shop List{% endblock %} 

{% block content %}

<link rel="stylesheet" href="{% static 'css/main.css' %}">

<div class="d-flex align-center justify-content-center row">
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-6 m-auto">
          <div class="card my-2">
            <form class="contact2-form validate-form">
              <span class="contact2-form-title"> Contact Us </span>
              <div
                class="wrap-input2 validate-input"
                data-validate="Name is required">
                <input class="input2" type="text" name="name" />
                <span class="focus-input2" data-placeholder="NAME"></span>
              </div>
              <div
                class="wrap-input2 validate-input"
                data-validate="Valid email is required: ex@abc.xyz">
                <input class="input2" type="text" name="email" />
                <span class="focus-input2" data-placeholder="EMAIL"></span>
              </div>
              <div
                class="wrap-input2 validate-input"
                data-validate="Message is required">
                <textarea class="input2" name="message"></textarea>
                <span class="focus-input2" data-placeholder="MESSAGE"></span>
              </div>
              <div class="container-contact2-form-btn">
                <div class="wrap-contact2-form-btn">
                  <div class="contact2-form-bgbtn"></div>
                  <button class="btn btn-warning">Send Your Message</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

carsaleswebsiteproject/car_management/templates/car_management/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock  %}

{% block content %}

<div class="d-flex align-center justify-content-center row">
    <div class="col-md-6">
        <h1>Welcome To <span style="font-size:40px; font-weight:900; color:green;">CurHut</span></h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium praesentium commodi deleniti consequuntur aliquam, et debitis suscipit, fuga error a vitae cum corrupti alias ut dolorem, reiciendis maxime pariatur? Dolore.</p>
        <div class="row align-center justify-content-left" style="max-width:300px;">
            <div class="col-sm-6"><a href="{% url 'shoppage' %}" class="btn btn-info">Shop Now</a></div>
            <div class="col-sm-6"><a href="{% url 'contact' %}" class="btn btn-dark">Contact</a></div>
        </div>
    </div>
    <div class="col-md-6">
        <img class="img-fluid" src=" {% static './car_banner.jpeg' %}" alt="">
    </div>
</div>
<div class="d-flex align-center justify-content-center row">
    <div class="card">
    
        <div class="card-header">
            <div class="row d-flex">
                <div class="col">
                    <a class="nav-link" href="/">All</a>
                </div>
                {% for brand in brands %}
                <div class="col">
                    <a class="nav-link" href="{% url 'car_list_by_brand_index' brand.slug %}">{{brand.name}}</a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-body">
            <h5>Showing {{ cars | length }} items</h5>
            <div class="row"> 
                
                {% for car in cars %}
                    <div class="col-md-4">
                        <div class="card my-2" >
                            <img src="{{ car.image.url }}" class="card-img-top" alt="{{ car.name }}">
                            <div class="card-body">
                                <h5>{{ car.name }}</h5>
                                <p class="text-muted">${{ car.price }}</p>
                                <p ><span class="badge bg-info">{{ car.brand}}</span></p>
                                <a href="{% url 'carDetailspage' car.id %}" class="btn btn-warning">View Details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    
               
            </div>
        </div>

        
    </div>
</div>


{% endblock  %}